begin;

alter table public.patients
  add column if not exists session_fee numeric(12, 2) not null default 0,
  add column if not exists billing_mode_override text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_patients_billing_mode_override'
      and conrelid = 'public.patients'::regclass
  ) then
    alter table public.patients
      add constraint ck_patients_billing_mode_override
      check (billing_mode_override is null or billing_mode_override in ('session', 'monthly'));
  end if;
end $$;

create table if not exists public.clinic_billing_settings (
  clinic_id uuid primary key references public.clinics (id) on delete cascade,
  default_billing_mode text not null default 'session' check (default_billing_mode in ('session', 'monthly')),
  monthly_generation_day integer not null default 5 check (monthly_generation_day between 1 and 28),
  timezone text not null default 'America/Sao_Paulo',
  auto_generate_monthly boolean not null default true,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clinic_asaas_settings (
  clinic_id uuid primary key references public.clinics (id) on delete cascade,
  reminder_preset text not null default 'standard',
  reminder_channels jsonb not null default '["email", "sms"]'::jsonb,
  reminder_timeline jsonb not null default '[{"days":2,"channel":"email"},{"hours":24,"channel":"email"}]'::jsonb,
  default_due_days integer not null default 2,
  late_fee_percent numeric(6, 2) not null default 2,
  interest_percent numeric(6, 2) not null default 1,
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_clinic_asaas_settings_preset'
      and conrelid = 'public.clinic_asaas_settings'::regclass
  ) then
    alter table public.clinic_asaas_settings
      add constraint ck_clinic_asaas_settings_preset
      check (reminder_preset in ('light', 'standard', 'intense'));
  end if;
end $$;

create table if not exists public.patient_monthly_statements (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  patient_id bigint not null references public.patients (id) on delete cascade,
  period_ym text not null,
  session_count integer not null default 0,
  unit_price numeric(12, 2) not null default 0,
  gross_amount numeric(12, 2) not null default 0,
  paid_amount numeric(12, 2) not null default 0,
  outstanding_amount numeric(12, 2) not null default 0,
  status text not null default 'open',
  asaas_charge_id text,
  generated_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id, patient_id, period_ym)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_patient_monthly_statements_period'
      and conrelid = 'public.patient_monthly_statements'::regclass
  ) then
    alter table public.patient_monthly_statements
      add constraint ck_patient_monthly_statements_period
      check (period_ym ~ '^[0-9]{4}-(0[1-9]|1[0-2])$');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_patient_monthly_statements_status'
      and conrelid = 'public.patient_monthly_statements'::regclass
  ) then
    alter table public.patient_monthly_statements
      add constraint ck_patient_monthly_statements_status
      check (status in ('open', 'partial', 'settled', 'cancelled'));
  end if;
end $$;

create table if not exists public.patient_monthly_statement_items (
  id bigint generated by default as identity primary key,
  statement_id bigint not null references public.patient_monthly_statements (id) on delete cascade,
  appointment_id bigint not null references public.appointments (id) on delete cascade,
  amount numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (statement_id, appointment_id)
);

alter table public.asaas_charges
  add column if not exists billing_mode text,
  add column if not exists statement_id bigint references public.patient_monthly_statements (id) on delete set null;

update public.asaas_charges
set billing_mode = coalesce(billing_mode, 'session')
where billing_mode is null;

alter table public.asaas_charges
  alter column billing_mode set not null,
  alter column billing_mode set default 'session';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_asaas_charges_billing_mode'
      and conrelid = 'public.asaas_charges'::regclass
  ) then
    alter table public.asaas_charges
      add constraint ck_asaas_charges_billing_mode
      check (billing_mode in ('session', 'monthly'));
  end if;
end $$;

create index if not exists idx_patient_monthly_statements_clinic_period on public.patient_monthly_statements (clinic_id, period_ym);
create index if not exists idx_patient_monthly_statements_patient_period on public.patient_monthly_statements (patient_id, period_ym);
create index if not exists idx_patient_monthly_statements_status on public.patient_monthly_statements (status);
create index if not exists idx_patient_monthly_items_statement on public.patient_monthly_statement_items (statement_id);
create index if not exists idx_asaas_charges_statement_id on public.asaas_charges (statement_id);

alter table public.clinic_billing_settings enable row level security;
alter table public.clinic_asaas_settings enable row level security;
alter table public.patient_monthly_statements enable row level security;
alter table public.patient_monthly_statement_items enable row level security;

drop policy if exists "clinic_billing_settings_select_clinic_member" on public.clinic_billing_settings;
drop policy if exists "clinic_billing_settings_insert_admin_professional" on public.clinic_billing_settings;
drop policy if exists "clinic_billing_settings_update_admin_professional" on public.clinic_billing_settings;
drop policy if exists "clinic_billing_settings_delete_admin_professional" on public.clinic_billing_settings;

create policy "clinic_billing_settings_select_clinic_member"
  on public.clinic_billing_settings for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_billing_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "clinic_billing_settings_insert_admin_professional"
  on public.clinic_billing_settings for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_billing_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_billing_settings_update_admin_professional"
  on public.clinic_billing_settings for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_billing_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_billing_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_billing_settings_delete_admin_professional"
  on public.clinic_billing_settings for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_billing_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "clinic_asaas_settings_select_clinic_member" on public.clinic_asaas_settings;
drop policy if exists "clinic_asaas_settings_insert_admin_professional" on public.clinic_asaas_settings;
drop policy if exists "clinic_asaas_settings_update_admin_professional" on public.clinic_asaas_settings;
drop policy if exists "clinic_asaas_settings_delete_admin_professional" on public.clinic_asaas_settings;

create policy "clinic_asaas_settings_select_clinic_member"
  on public.clinic_asaas_settings for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_asaas_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "clinic_asaas_settings_insert_admin_professional"
  on public.clinic_asaas_settings for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_asaas_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_asaas_settings_update_admin_professional"
  on public.clinic_asaas_settings for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_asaas_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_asaas_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_asaas_settings_delete_admin_professional"
  on public.clinic_asaas_settings for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_asaas_settings.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "patient_monthly_statements_select_clinic_member" on public.patient_monthly_statements;
drop policy if exists "patient_monthly_statements_insert_admin_professional" on public.patient_monthly_statements;
drop policy if exists "patient_monthly_statements_update_admin_professional" on public.patient_monthly_statements;
drop policy if exists "patient_monthly_statements_delete_admin_professional" on public.patient_monthly_statements;

create policy "patient_monthly_statements_select_clinic_member"
  on public.patient_monthly_statements for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_monthly_statements.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "patient_monthly_statements_insert_admin_professional"
  on public.patient_monthly_statements for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_monthly_statements.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "patient_monthly_statements_update_admin_professional"
  on public.patient_monthly_statements for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_monthly_statements.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_monthly_statements.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "patient_monthly_statements_delete_admin_professional"
  on public.patient_monthly_statements for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_monthly_statements.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "patient_monthly_statement_items_select_clinic_member" on public.patient_monthly_statement_items;
drop policy if exists "patient_monthly_statement_items_insert_admin_professional" on public.patient_monthly_statement_items;
drop policy if exists "patient_monthly_statement_items_update_admin_professional" on public.patient_monthly_statement_items;
drop policy if exists "patient_monthly_statement_items_delete_admin_professional" on public.patient_monthly_statement_items;

create policy "patient_monthly_statement_items_select_clinic_member"
  on public.patient_monthly_statement_items for select
  using (
    exists (
      select 1
      from public.patient_monthly_statements pms
      join public.clinic_members cm on cm.clinic_id = pms.clinic_id
      where pms.id = patient_monthly_statement_items.statement_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "patient_monthly_statement_items_insert_admin_professional"
  on public.patient_monthly_statement_items for insert
  with check (
    exists (
      select 1
      from public.patient_monthly_statements pms
      join public.clinic_members cm on cm.clinic_id = pms.clinic_id
      where pms.id = patient_monthly_statement_items.statement_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "patient_monthly_statement_items_update_admin_professional"
  on public.patient_monthly_statement_items for update
  using (
    exists (
      select 1
      from public.patient_monthly_statements pms
      join public.clinic_members cm on cm.clinic_id = pms.clinic_id
      where pms.id = patient_monthly_statement_items.statement_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.patient_monthly_statements pms
      join public.clinic_members cm on cm.clinic_id = pms.clinic_id
      where pms.id = patient_monthly_statement_items.statement_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "patient_monthly_statement_items_delete_admin_professional"
  on public.patient_monthly_statement_items for delete
  using (
    exists (
      select 1
      from public.patient_monthly_statements pms
      join public.clinic_members cm on cm.clinic_id = pms.clinic_id
      where pms.id = patient_monthly_statement_items.statement_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

commit;
