begin;

create table if not exists public.platform_superadmins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  email text,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tenant_subscriptions (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  plan_code text not null default 'starter',
  status text not null default 'active' check (status in ('trialing', 'active', 'past_due', 'suspended', 'cancelled')),
  billing_provider text not null default 'manual' check (billing_provider in ('manual', 'asaas')),
  asaas_customer_id text,
  asaas_subscription_id text,
  trial_ends_at timestamptz,
  current_period_start timestamptz,
  current_period_end timestamptz,
  payment_grace_until timestamptz,
  next_charge_at timestamptz,
  blocked_at timestamptz,
  suspended_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id)
);

insert into public.tenant_subscriptions (clinic_id, plan_code, status, billing_provider)
select c.id, 'starter', 'active', 'manual'
from public.clinics c
where not exists (
  select 1
  from public.tenant_subscriptions ts
  where ts.clinic_id = c.id
);

create table if not exists public.tenant_feature_flags (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  feature_key text not null,
  enabled boolean not null default false,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id, feature_key)
);

create table if not exists public.platform_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  actor_type text not null check (actor_type in ('superadmin', 'system')),
  action text not null,
  target_type text not null,
  target_id text,
  clinic_id uuid references public.clinics (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_tenant_subscriptions_clinic_status on public.tenant_subscriptions (clinic_id, status);
create index if not exists idx_tenant_subscriptions_status on public.tenant_subscriptions (status);
create index if not exists idx_tenant_subscriptions_provider on public.tenant_subscriptions (billing_provider);
create index if not exists idx_tenant_feature_flags_clinic on public.tenant_feature_flags (clinic_id, feature_key);
create index if not exists idx_platform_audit_logs_created_at on public.platform_audit_logs (created_at desc);
create index if not exists idx_platform_audit_logs_clinic_created_at on public.platform_audit_logs (clinic_id, created_at desc);

alter table public.platform_superadmins enable row level security;
alter table public.tenant_subscriptions enable row level security;
alter table public.tenant_feature_flags enable row level security;
alter table public.platform_audit_logs enable row level security;

drop policy if exists "platform_superadmins_select_self" on public.platform_superadmins;
drop policy if exists "tenant_subscriptions_select_member" on public.tenant_subscriptions;
drop policy if exists "tenant_feature_flags_select_member" on public.tenant_feature_flags;
drop policy if exists "platform_audit_logs_select_superadmin" on public.platform_audit_logs;

create policy "platform_superadmins_select_self"
  on public.platform_superadmins for select
  using (auth.uid() = user_id);

create policy "tenant_subscriptions_select_member"
  on public.tenant_subscriptions for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = tenant_subscriptions.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "tenant_feature_flags_select_member"
  on public.tenant_feature_flags for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = tenant_feature_flags.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "platform_audit_logs_select_superadmin"
  on public.platform_audit_logs for select
  using (
    exists (
      select 1
      from public.platform_superadmins ps
      where ps.user_id = auth.uid()
        and ps.active = true
    )
  );

commit;
