begin;

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  user_id uuid not null,
  patient_id bigint references public.patients (id) on delete set null,
  note_id bigint references public.notes (id) on delete set null,
  operation text not null default 'audio_transcription',
  provider text not null default 'google',
  model text not null,
  status text not null default 'success',
  input_audio_bytes integer not null default 0,
  input_seconds numeric(12, 2) not null default 0,
  input_tokens_estimated integer not null default 0,
  output_tokens_estimated integer not null default 0,
  total_tokens_estimated integer not null default 0,
  estimated_cost numeric(14, 6) not null default 0,
  currency text not null default 'BRL',
  error_message text,
  request_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_ai_usage_events_status'
      and conrelid = 'public.ai_usage_events'::regclass
  ) then
    alter table public.ai_usage_events
      add constraint ck_ai_usage_events_status
      check (status in ('success', 'failed'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_ai_usage_events_operation'
      and conrelid = 'public.ai_usage_events'::regclass
  ) then
    alter table public.ai_usage_events
      add constraint ck_ai_usage_events_operation
      check (operation in ('audio_transcription'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_ai_usage_events_non_negative'
      and conrelid = 'public.ai_usage_events'::regclass
  ) then
    alter table public.ai_usage_events
      add constraint ck_ai_usage_events_non_negative
      check (
        input_audio_bytes >= 0
        and input_seconds >= 0
        and input_tokens_estimated >= 0
        and output_tokens_estimated >= 0
        and total_tokens_estimated >= 0
        and estimated_cost >= 0
      );
  end if;
end $$;

create index if not exists idx_ai_usage_events_clinic_created_at
  on public.ai_usage_events (clinic_id, created_at desc);
create index if not exists idx_ai_usage_events_clinic_status_created_at
  on public.ai_usage_events (clinic_id, status, created_at desc);
create index if not exists idx_ai_usage_events_clinic_model_created_at
  on public.ai_usage_events (clinic_id, model, created_at desc);
create index if not exists idx_ai_usage_events_patient_created_at
  on public.ai_usage_events (patient_id, created_at desc);

alter table public.ai_usage_events enable row level security;

drop policy if exists "ai_usage_events_select_clinic_member" on public.ai_usage_events;
drop policy if exists "ai_usage_events_insert_admin_professional" on public.ai_usage_events;
drop policy if exists "ai_usage_events_update_admin_professional" on public.ai_usage_events;
drop policy if exists "ai_usage_events_delete_admin_professional" on public.ai_usage_events;

create policy "ai_usage_events_select_clinic_member"
  on public.ai_usage_events for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = ai_usage_events.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "ai_usage_events_insert_admin_professional"
  on public.ai_usage_events for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = ai_usage_events.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "ai_usage_events_update_admin_professional"
  on public.ai_usage_events for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = ai_usage_events.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = ai_usage_events.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "ai_usage_events_delete_admin_professional"
  on public.ai_usage_events for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = ai_usage_events.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

commit;
