begin;

create extension if not exists pgcrypto;

create table if not exists public.clinics (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clinic_members (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'professional', 'secretary')),
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id, user_id)
);

alter table public.patients add column if not exists clinic_id uuid references public.clinics (id) on delete cascade;
alter table public.notes add column if not exists clinic_id uuid references public.clinics (id) on delete cascade;
alter table public.appointments add column if not exists clinic_id uuid references public.clinics (id) on delete cascade;
alter table public.financial_records add column if not exists clinic_id uuid references public.clinics (id) on delete cascade;

create index if not exists idx_clinics_owner_user_id on public.clinics (owner_user_id);
create index if not exists idx_clinic_members_user on public.clinic_members (user_id, active);
create index if not exists idx_clinic_members_clinic on public.clinic_members (clinic_id, role, active);
create index if not exists idx_patients_clinic_id on public.patients (clinic_id);
create index if not exists idx_notes_clinic_id_created_at on public.notes (clinic_id, created_at desc);
create index if not exists idx_appointments_clinic_id_start on public.appointments (clinic_id, start_time);
create index if not exists idx_financial_clinic_id_date on public.financial_records (clinic_id, date desc);

create temp table _legacy_users as
select distinct user_id
from (
  select user_id from public.patients
  union
  select user_id from public.notes
  union
  select user_id from public.appointments
  union
  select user_id from public.financial_records
) as users
where user_id is not null;

insert into public.clinics (name, owner_user_id)
select 'Clinica ' || substr(lu.user_id::text, 1, 8), lu.user_id
from _legacy_users lu
where not exists (
  select 1
  from public.clinics c
  where c.owner_user_id = lu.user_id
);

create temp table _user_clinic_map as
select
  lu.user_id,
  (
    select c.id
    from public.clinics c
    where c.owner_user_id = lu.user_id
    order by c.created_at asc
    limit 1
  ) as clinic_id
from _legacy_users lu;

insert into public.clinic_members (clinic_id, user_id, role, active)
select ucm.clinic_id, ucm.user_id, 'admin', true
from _user_clinic_map ucm
where ucm.clinic_id is not null
on conflict (clinic_id, user_id)
do update set role = excluded.role, active = true;

update public.patients p
set clinic_id = ucm.clinic_id
from _user_clinic_map ucm
where p.clinic_id is null and p.user_id = ucm.user_id;

update public.notes n
set clinic_id = ucm.clinic_id
from _user_clinic_map ucm
where n.clinic_id is null and n.user_id = ucm.user_id;

update public.appointments a
set clinic_id = ucm.clinic_id
from _user_clinic_map ucm
where a.clinic_id is null and a.user_id = ucm.user_id;

update public.financial_records f
set clinic_id = ucm.clinic_id
from _user_clinic_map ucm
where f.clinic_id is null and f.user_id = ucm.user_id;

do $$
begin
  if exists (select 1 from public.patients where clinic_id is null) then
    raise exception 'Backfill failed: patients.clinic_id has null rows.';
  end if;
  if exists (select 1 from public.notes where clinic_id is null) then
    raise exception 'Backfill failed: notes.clinic_id has null rows.';
  end if;
  if exists (select 1 from public.appointments where clinic_id is null) then
    raise exception 'Backfill failed: appointments.clinic_id has null rows.';
  end if;
  if exists (select 1 from public.financial_records where clinic_id is null) then
    raise exception 'Backfill failed: financial_records.clinic_id has null rows.';
  end if;
end $$;

alter table public.patients alter column clinic_id set not null;
alter table public.notes alter column clinic_id set not null;
alter table public.appointments alter column clinic_id set not null;
alter table public.financial_records alter column clinic_id set not null;

create table if not exists public.appointment_series (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  frequency text not null check (frequency in ('weekly', 'biweekly', 'monthly')),
  until_date date not null,
  template_start_time timestamptz not null,
  session_type text not null default 'individual' check (session_type in ('individual', 'couple')),
  session_mode text not null default 'in_person' check (session_mode in ('in_person', 'online')),
  online_meeting_url text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_appointment_series_clinic on public.appointment_series (clinic_id, active);
create index if not exists idx_appointment_series_until_date on public.appointment_series (until_date);

alter table public.appointments add column if not exists series_id bigint references public.appointment_series (id) on delete set null;
alter table public.appointments add column if not exists series_sequence integer;
alter table public.appointments add column if not exists is_exception boolean not null default false;
alter table public.appointments add column if not exists session_type text;
alter table public.appointments add column if not exists secondary_patient_id bigint references public.patients (id) on delete set null;
alter table public.appointments add column if not exists session_mode text;
alter table public.appointments add column if not exists online_meeting_url text;
alter table public.appointments add column if not exists duration_minutes integer not null default 60;

update public.appointments set session_type = coalesce(session_type, 'individual');
update public.appointments set session_mode = coalesce(session_mode, 'in_person');
update public.appointments set duration_minutes = 60 where duration_minutes is distinct from 60;

alter table public.appointments alter column session_type set not null;
alter table public.appointments alter column session_mode set not null;
alter table public.appointments alter column duration_minutes set not null;
alter table public.appointments alter column duration_minutes set default 60;

create index if not exists idx_appointments_series on public.appointments (series_id, series_sequence);
create index if not exists idx_appointments_secondary_patient on public.appointments (secondary_patient_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_appointments_duration_60'
      and conrelid = 'public.appointments'::regclass
  ) then
    alter table public.appointments
      add constraint ck_appointments_duration_60 check (duration_minutes = 60);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_appointments_couple_secondary'
      and conrelid = 'public.appointments'::regclass
  ) then
    alter table public.appointments
      add constraint ck_appointments_couple_secondary
      check (session_type <> 'couple' or secondary_patient_id is not null);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_appointments_online_link'
      and conrelid = 'public.appointments'::regclass
  ) then
    alter table public.appointments
      add constraint ck_appointments_online_link
      check (session_mode = 'online' or online_meeting_url is null);
  end if;
end $$;

create table if not exists public.patient_billing_profile (
  patient_id bigint primary key references public.patients (id) on delete cascade,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  asaas_customer_id text not null,
  billing_owner_user_id uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_patient_billing_profile_clinic_patient on public.patient_billing_profile (clinic_id, patient_id);
create unique index if not exists idx_patient_billing_profile_asaas_customer on public.patient_billing_profile (asaas_customer_id);

create table if not exists public.asaas_charges (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  patient_id bigint not null references public.patients (id) on delete cascade,
  appointment_id bigint references public.appointments (id) on delete set null,
  asaas_charge_id text not null unique,
  status text not null,
  value numeric(12, 2) not null,
  due_date date not null,
  last_payload jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_asaas_charges_patient on public.asaas_charges (patient_id);
create index if not exists idx_asaas_charges_status on public.asaas_charges (status);
create index if not exists idx_asaas_charges_due_date on public.asaas_charges (due_date);
create index if not exists idx_asaas_charges_clinic_patient on public.asaas_charges (clinic_id, patient_id);

alter table public.clinics enable row level security;
alter table public.clinic_members enable row level security;
alter table public.appointment_series enable row level security;
alter table public.patient_billing_profile enable row level security;
alter table public.asaas_charges enable row level security;

drop policy if exists "patients_select_own" on public.patients;
drop policy if exists "patients_insert_own" on public.patients;
drop policy if exists "patients_update_own" on public.patients;
drop policy if exists "patients_delete_own" on public.patients;
drop policy if exists "notes_select_own" on public.notes;
drop policy if exists "notes_insert_own" on public.notes;
drop policy if exists "notes_update_own" on public.notes;
drop policy if exists "notes_delete_own" on public.notes;
drop policy if exists "appointments_select_own" on public.appointments;
drop policy if exists "appointments_insert_own" on public.appointments;
drop policy if exists "appointments_update_own" on public.appointments;
drop policy if exists "appointments_delete_own" on public.appointments;
drop policy if exists "financial_select_own" on public.financial_records;
drop policy if exists "financial_insert_own" on public.financial_records;
drop policy if exists "financial_update_own" on public.financial_records;
drop policy if exists "financial_delete_own" on public.financial_records;

drop policy if exists "clinics_select_member" on public.clinics;
drop policy if exists "clinics_insert_owner" on public.clinics;
drop policy if exists "clinics_update_admin" on public.clinics;
drop policy if exists "clinics_delete_admin" on public.clinics;
drop policy if exists "clinic_members_select_member" on public.clinic_members;
drop policy if exists "clinic_members_insert_admin" on public.clinic_members;
drop policy if exists "clinic_members_update_admin" on public.clinic_members;
drop policy if exists "clinic_members_delete_admin" on public.clinic_members;
drop policy if exists "patients_select_clinic_member" on public.patients;
drop policy if exists "patients_insert_clinic_member" on public.patients;
drop policy if exists "patients_update_clinic_member" on public.patients;
drop policy if exists "patients_delete_clinic_member" on public.patients;
drop policy if exists "notes_select_clinical" on public.notes;
drop policy if exists "notes_insert_clinical" on public.notes;
drop policy if exists "notes_update_clinical" on public.notes;
drop policy if exists "notes_delete_clinical" on public.notes;
drop policy if exists "appointments_select_clinic_member" on public.appointments;
drop policy if exists "appointments_insert_clinic_member" on public.appointments;
drop policy if exists "appointments_update_clinic_member" on public.appointments;
drop policy if exists "appointments_delete_clinic_member" on public.appointments;
drop policy if exists "financial_select_clinic_member" on public.financial_records;
drop policy if exists "financial_insert_clinic_member" on public.financial_records;
drop policy if exists "financial_update_clinic_member" on public.financial_records;
drop policy if exists "financial_delete_clinic_member" on public.financial_records;
drop policy if exists "appointment_series_select_clinic_member" on public.appointment_series;
drop policy if exists "appointment_series_insert_clinic_member" on public.appointment_series;
drop policy if exists "appointment_series_update_clinic_member" on public.appointment_series;
drop policy if exists "appointment_series_delete_clinic_member" on public.appointment_series;
drop policy if exists "billing_profile_select_clinic_member" on public.patient_billing_profile;
drop policy if exists "billing_profile_insert_clinic_member" on public.patient_billing_profile;
drop policy if exists "billing_profile_update_clinic_member" on public.patient_billing_profile;
drop policy if exists "billing_profile_delete_clinic_member" on public.patient_billing_profile;
drop policy if exists "asaas_charges_select_clinic_member" on public.asaas_charges;
drop policy if exists "asaas_charges_insert_clinic_member" on public.asaas_charges;
drop policy if exists "asaas_charges_update_clinic_member" on public.asaas_charges;
drop policy if exists "asaas_charges_delete_clinic_member" on public.asaas_charges;

create policy "clinics_select_member"
  on public.clinics for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinics.id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "clinics_insert_owner"
  on public.clinics for insert
  with check (owner_user_id = auth.uid());

create policy "clinics_update_admin"
  on public.clinics for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinics.id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinics.id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  );

create policy "clinics_delete_admin"
  on public.clinics for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinics.id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  );

create policy "clinic_members_select_member"
  on public.clinic_members for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_members.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "clinic_members_insert_admin"
  on public.clinic_members for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_members.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  );

create policy "clinic_members_update_admin"
  on public.clinic_members for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_members.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_members.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  );

create policy "clinic_members_delete_admin"
  on public.clinic_members for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_members.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role = 'admin'
    )
  );

create policy "patients_select_clinic_member"
  on public.patients for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patients.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "patients_insert_clinic_member"
  on public.patients for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patients.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "patients_update_clinic_member"
  on public.patients for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patients.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patients.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "patients_delete_clinic_member"
  on public.patients for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patients.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "notes_select_clinical"
  on public.notes for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = notes.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "notes_insert_clinical"
  on public.notes for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = notes.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "notes_update_clinical"
  on public.notes for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = notes.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = notes.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "notes_delete_clinical"
  on public.notes for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = notes.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "appointments_select_clinic_member"
  on public.appointments for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointments.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointments_insert_clinic_member"
  on public.appointments for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointments.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointments_update_clinic_member"
  on public.appointments for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointments.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointments.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointments_delete_clinic_member"
  on public.appointments for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointments.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "financial_select_clinic_member"
  on public.financial_records for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = financial_records.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "financial_insert_clinic_member"
  on public.financial_records for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = financial_records.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "financial_update_clinic_member"
  on public.financial_records for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = financial_records.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = financial_records.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "financial_delete_clinic_member"
  on public.financial_records for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = financial_records.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointment_series_select_clinic_member"
  on public.appointment_series for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointment_series.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointment_series_insert_clinic_member"
  on public.appointment_series for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointment_series.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointment_series_update_clinic_member"
  on public.appointment_series for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointment_series.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointment_series.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "appointment_series_delete_clinic_member"
  on public.appointment_series for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = appointment_series.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "billing_profile_select_clinic_member"
  on public.patient_billing_profile for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_billing_profile.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "billing_profile_insert_clinic_member"
  on public.patient_billing_profile for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_billing_profile.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "billing_profile_update_clinic_member"
  on public.patient_billing_profile for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_billing_profile.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_billing_profile.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "billing_profile_delete_clinic_member"
  on public.patient_billing_profile for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = patient_billing_profile.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "asaas_charges_select_clinic_member"
  on public.asaas_charges for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = asaas_charges.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "asaas_charges_insert_clinic_member"
  on public.asaas_charges for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = asaas_charges.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "asaas_charges_update_clinic_member"
  on public.asaas_charges for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = asaas_charges.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = asaas_charges.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "asaas_charges_delete_clinic_member"
  on public.asaas_charges for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = asaas_charges.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

commit;
