begin;

create table if not exists public.clinic_note_templates (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  user_id uuid references auth.users (id) on delete cascade,
  name text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_note_templates_clinic on public.clinic_note_templates (clinic_id);

alter table public.clinic_note_templates enable row level security;

create policy "templates_select_clinic_member"
  on public.clinic_note_templates for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_note_templates.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "templates_insert_clinic_member"
  on public.clinic_note_templates for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_note_templates.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "templates_update_owner"
  on public.clinic_note_templates for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_note_templates.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_note_templates.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "templates_delete_owner"
  on public.clinic_note_templates for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_note_templates.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

commit;
