begin;

alter table public.appointments
  add column if not exists provider_user_id uuid references auth.users (id) on delete cascade;

update public.appointments
set provider_user_id = coalesce(provider_user_id, user_id)
where provider_user_id is null;

alter table public.appointments
  alter column provider_user_id set not null;

alter table public.appointments
  add column if not exists is_block boolean not null default false,
  add column if not exists google_event_id text,
  add column if not exists google_calendar_id text,
  add column if not exists google_sync_status text default 'pending',
  add column if not exists google_last_synced_at timestamptz;

update public.appointments
set google_sync_status = coalesce(google_sync_status, 'pending')
where google_sync_status is null;

alter table public.notes
  add column if not exists source text;

update public.notes
set source = 'manual'
where source is null;

alter table public.notes
  alter column source set not null,
  alter column source set default 'manual';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_notes_source'
      and conrelid = 'public.notes'::regclass
  ) then
    alter table public.notes
      add constraint ck_notes_source
      check (source in ('audio', 'quick', 'manual'));
  end if;
end $$;

create table if not exists public.google_user_connections (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  google_email text,
  access_token_encrypted text not null,
  refresh_token_encrypted text not null,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id, user_id)
);

create table if not exists public.google_watch_channels (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  calendar_id text not null default 'primary',
  channel_id text not null unique,
  resource_id text not null,
  expiration_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.calendar_blocks (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  provider_user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  google_event_id text,
  source text not null default 'manual',
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_calendar_blocks_time'
      and conrelid = 'public.calendar_blocks'::regclass
  ) then
    alter table public.calendar_blocks
      add constraint ck_calendar_blocks_time
      check (end_time > start_time);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ck_calendar_blocks_source'
      and conrelid = 'public.calendar_blocks'::regclass
  ) then
    alter table public.calendar_blocks
      add constraint ck_calendar_blocks_source
      check (source in ('manual', 'google_external'));
  end if;
end $$;

create index if not exists idx_appointments_provider on public.appointments (provider_user_id, start_time);
create index if not exists idx_appointments_google_event on public.appointments (google_event_id);
create index if not exists idx_appointments_is_block_start on public.appointments (is_block, start_time);
create index if not exists idx_google_user_connections_clinic_user on public.google_user_connections (clinic_id, user_id, active);
create index if not exists idx_google_watch_channels_clinic_user on public.google_watch_channels (clinic_id, user_id, active);
create index if not exists idx_calendar_blocks_clinic_provider_start on public.calendar_blocks (clinic_id, provider_user_id, start_time);
create index if not exists idx_calendar_blocks_google_event on public.calendar_blocks (google_event_id);

alter table public.google_user_connections enable row level security;
alter table public.google_watch_channels enable row level security;
alter table public.calendar_blocks enable row level security;

drop policy if exists "google_user_connections_select_own" on public.google_user_connections;
drop policy if exists "google_user_connections_insert_own" on public.google_user_connections;
drop policy if exists "google_user_connections_update_own" on public.google_user_connections;
drop policy if exists "google_user_connections_delete_own" on public.google_user_connections;

create policy "google_user_connections_select_own"
  on public.google_user_connections for select
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_user_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_user_connections_insert_own"
  on public.google_user_connections for insert
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_user_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_user_connections_update_own"
  on public.google_user_connections for update
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_user_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_user_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_user_connections_delete_own"
  on public.google_user_connections for delete
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_user_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "google_watch_channels_select_clinic" on public.google_watch_channels;
drop policy if exists "google_watch_channels_insert_clinic" on public.google_watch_channels;
drop policy if exists "google_watch_channels_update_clinic" on public.google_watch_channels;
drop policy if exists "google_watch_channels_delete_clinic" on public.google_watch_channels;

create policy "google_watch_channels_select_clinic"
  on public.google_watch_channels for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_watch_channels.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_watch_channels_insert_clinic"
  on public.google_watch_channels for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_watch_channels.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_watch_channels_update_clinic"
  on public.google_watch_channels for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_watch_channels.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_watch_channels.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "google_watch_channels_delete_clinic"
  on public.google_watch_channels for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = google_watch_channels.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "calendar_blocks_select_clinic_member" on public.calendar_blocks;
drop policy if exists "calendar_blocks_insert_clinic_clinical" on public.calendar_blocks;
drop policy if exists "calendar_blocks_update_clinic_clinical" on public.calendar_blocks;
drop policy if exists "calendar_blocks_delete_clinic_clinical" on public.calendar_blocks;

create policy "calendar_blocks_select_clinic_member"
  on public.calendar_blocks for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = calendar_blocks.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "calendar_blocks_insert_clinic_clinical"
  on public.calendar_blocks for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = calendar_blocks.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "calendar_blocks_update_clinic_clinical"
  on public.calendar_blocks for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = calendar_blocks.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = calendar_blocks.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "calendar_blocks_delete_clinic_clinical"
  on public.calendar_blocks for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = calendar_blocks.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

commit;
