begin;

create table if not exists public.clinic_evolution_connections (
  clinic_id uuid primary key references public.clinics (id) on delete cascade,
  api_base_url text not null,
  instance_name text not null,
  api_token_encrypted text not null,
  webhook_secret text,
  status text not null default 'disconnected' check (status in ('connected', 'disconnected', 'error')),
  last_error text,
  last_seen_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_by_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inbox_threads (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  channel text not null default 'whatsapp',
  external_thread_id text not null,
  contact_name text,
  contact_phone text,
  status text not null default 'open' check (status in ('open', 'pending', 'resolved', 'blocked')),
  assigned_user_id uuid references auth.users (id) on delete set null,
  labels jsonb not null default '[]'::jsonb,
  unread_count integer not null default 0 check (unread_count >= 0),
  last_message_preview text,
  last_message_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (clinic_id, channel, external_thread_id)
);

create table if not exists public.inbox_messages (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  thread_id bigint not null references public.inbox_threads (id) on delete cascade,
  direction text not null check (direction in ('inbound', 'outbound', 'system')),
  message_type text not null default 'text',
  content text,
  external_message_id text,
  sender_name text,
  sender_phone text,
  sent_by_user_id uuid references auth.users (id) on delete set null,
  sent_at timestamptz not null default timezone('utc', now()),
  status text not null default 'received' check (status in ('queued', 'sent', 'received', 'failed')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_inbox_messages_external_unique
  on public.inbox_messages (clinic_id, external_message_id)
  where external_message_id is not null;

create index if not exists idx_inbox_threads_clinic_status_updated
  on public.inbox_threads (clinic_id, status, last_message_at desc);
create index if not exists idx_inbox_threads_clinic_assigned
  on public.inbox_threads (clinic_id, assigned_user_id, updated_at desc);
create index if not exists idx_inbox_messages_thread_sent
  on public.inbox_messages (thread_id, sent_at asc);
create index if not exists idx_inbox_messages_clinic_sent
  on public.inbox_messages (clinic_id, sent_at desc);

alter table public.clinic_evolution_connections enable row level security;
alter table public.inbox_threads enable row level security;
alter table public.inbox_messages enable row level security;

drop policy if exists "clinic_evolution_connections_select_member" on public.clinic_evolution_connections;
drop policy if exists "clinic_evolution_connections_insert_admin_professional" on public.clinic_evolution_connections;
drop policy if exists "clinic_evolution_connections_update_admin_professional" on public.clinic_evolution_connections;
drop policy if exists "clinic_evolution_connections_delete_admin_professional" on public.clinic_evolution_connections;

create policy "clinic_evolution_connections_select_member"
  on public.clinic_evolution_connections for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_evolution_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "clinic_evolution_connections_insert_admin_professional"
  on public.clinic_evolution_connections for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_evolution_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_evolution_connections_update_admin_professional"
  on public.clinic_evolution_connections for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_evolution_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_evolution_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

create policy "clinic_evolution_connections_delete_admin_professional"
  on public.clinic_evolution_connections for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = clinic_evolution_connections.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
        and cm.role in ('admin', 'professional')
    )
  );

drop policy if exists "inbox_threads_select_member" on public.inbox_threads;
drop policy if exists "inbox_threads_insert_member" on public.inbox_threads;
drop policy if exists "inbox_threads_update_member" on public.inbox_threads;
drop policy if exists "inbox_threads_delete_member" on public.inbox_threads;

create policy "inbox_threads_select_member"
  on public.inbox_threads for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_threads.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_threads_insert_member"
  on public.inbox_threads for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_threads.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_threads_update_member"
  on public.inbox_threads for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_threads.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_threads.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_threads_delete_member"
  on public.inbox_threads for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_threads.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

drop policy if exists "inbox_messages_select_member" on public.inbox_messages;
drop policy if exists "inbox_messages_insert_member" on public.inbox_messages;
drop policy if exists "inbox_messages_update_member" on public.inbox_messages;
drop policy if exists "inbox_messages_delete_member" on public.inbox_messages;

create policy "inbox_messages_select_member"
  on public.inbox_messages for select
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_messages.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_messages_insert_member"
  on public.inbox_messages for insert
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_messages.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_messages_update_member"
  on public.inbox_messages for update
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_messages.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_messages.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

create policy "inbox_messages_delete_member"
  on public.inbox_messages for delete
  using (
    exists (
      select 1
      from public.clinic_members cm
      where cm.clinic_id = inbox_messages.clinic_id
        and cm.user_id = auth.uid()
        and cm.active = true
    )
  );

commit;
