begin;

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  email text,
  phone text,
  birth_date date,
  cpf text,
  address text,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  patient_id bigint references public.patients (id) on delete set null,
  complaint text,
  intervention text,
  next_focus text,
  observations text,
  created_at timestamptz not null default timezone('utc', now()),
  status text not null default 'draft' check (status in ('draft', 'final'))
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  patient_id bigint not null references public.patients (id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'scheduled',
  notes text
);

create table if not exists public.financial_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  patient_id bigint references public.patients (id) on delete set null,
  amount numeric(12, 2) not null,
  type text not null check (type in ('income', 'expense')),
  category text,
  description text,
  date timestamptz not null default timezone('utc', now()),
  status text not null default 'pending' check (status in ('pending', 'paid'))
);

create index if not exists idx_patients_user_id on public.patients (user_id);
create index if not exists idx_notes_user_id_created_at on public.notes (user_id, created_at desc);
create index if not exists idx_notes_patient_id on public.notes (patient_id);
create index if not exists idx_appointments_user_id_start_time on public.appointments (user_id, start_time);
create index if not exists idx_appointments_patient_id on public.appointments (patient_id);
create index if not exists idx_financial_user_id_date on public.financial_records (user_id, date desc);
create index if not exists idx_financial_patient_id on public.financial_records (patient_id);

alter table public.patients enable row level security;
alter table public.notes enable row level security;
alter table public.appointments enable row level security;
alter table public.financial_records enable row level security;

drop policy if exists "patients_select_own" on public.patients;
drop policy if exists "patients_insert_own" on public.patients;
drop policy if exists "patients_update_own" on public.patients;
drop policy if exists "patients_delete_own" on public.patients;

create policy "patients_select_own"
  on public.patients for select
  using (auth.uid() = user_id);

create policy "patients_insert_own"
  on public.patients for insert
  with check (auth.uid() = user_id);

create policy "patients_update_own"
  on public.patients for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "patients_delete_own"
  on public.patients for delete
  using (auth.uid() = user_id);

drop policy if exists "notes_select_own" on public.notes;
drop policy if exists "notes_insert_own" on public.notes;
drop policy if exists "notes_update_own" on public.notes;
drop policy if exists "notes_delete_own" on public.notes;

create policy "notes_select_own"
  on public.notes for select
  using (auth.uid() = user_id);

create policy "notes_insert_own"
  on public.notes for insert
  with check (auth.uid() = user_id);

create policy "notes_update_own"
  on public.notes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "notes_delete_own"
  on public.notes for delete
  using (auth.uid() = user_id);

drop policy if exists "appointments_select_own" on public.appointments;
drop policy if exists "appointments_insert_own" on public.appointments;
drop policy if exists "appointments_update_own" on public.appointments;
drop policy if exists "appointments_delete_own" on public.appointments;

create policy "appointments_select_own"
  on public.appointments for select
  using (auth.uid() = user_id);

create policy "appointments_insert_own"
  on public.appointments for insert
  with check (auth.uid() = user_id);

create policy "appointments_update_own"
  on public.appointments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "appointments_delete_own"
  on public.appointments for delete
  using (auth.uid() = user_id);

drop policy if exists "financial_select_own" on public.financial_records;
drop policy if exists "financial_insert_own" on public.financial_records;
drop policy if exists "financial_update_own" on public.financial_records;
drop policy if exists "financial_delete_own" on public.financial_records;

create policy "financial_select_own"
  on public.financial_records for select
  using (auth.uid() = user_id);

create policy "financial_insert_own"
  on public.financial_records for insert
  with check (auth.uid() = user_id);

create policy "financial_update_own"
  on public.financial_records for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "financial_delete_own"
  on public.financial_records for delete
  using (auth.uid() = user_id);

commit;
